name: Flutter Build & Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'  # Specify the Flutter version you want to use

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android app
        run: flutter build apk

      #- name: Build Windows app
        #run: flutter build windows

      - name: Build web app
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/app/outputs/flutter-apk/app-release.apk
            ./build/windows/runner/Runner.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
